version: '3'
services:
  api:
    container_name: workmate-test
    restart: always
    build: ./
    environment:
      - DATABASE_URL=db/cats.db
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
